Repository sous-chefs/rundeck, pull requests merged in 2021-11, with the labels that each got.

#284 Bintray Deprecated. Updated to new official repo.
  CHANGELOG.md
  libraries/helpers.rb
  resources/repository.rb
  resources/server_install.rb
  test/integration/server_install/controls/server_spec.rb
Labels: Waiting on Contributor, Release: Major

#285 Feature/chef 17
  .circleci/config.yml
  CHANGELOG.md
  Dangerfile
  metadata.rb
  resources/apache.rb
  resources/cli.rb
  resources/dependencies.rb
  resources/plugin.rb
  resources/project.rb
  resources/repository.rb
  resources/server_install.rb
Labels: Release: Major

#286 Automated PR: Cookstyle Changes
  CHANGELOG.md
  metadata.rb
  resources/server_install.rb
Labels: Release: Minor
